services:
  proxy:
    container_name: luxuria-proxy

    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:6969/api
        VITE_NODE_ENV: stage

    ports:
      - "6969:6969"
    volumes:
      - ./proxy/Caddyfile.stage:/etc/caddy/Caddyfile

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        NODE_ENV: stage

    environment:
      NODE_ENV: stage
      carrersKey: ${carrersKey}
      contactUsKey: ${contactUsKey}
      RECIPIENT: ${RECIPIENT}

    restart: unless-stopped
