services:
  proxy:
    container_name: luxuria-proxy

    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
        VITE_NODE_ENV: stage
        VITE_carrersKey: ${VITE_carrersKey}
        VITE_contactUsKey: ${VITE_contactUsKey}

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/Caddyfile.stage:/etc/caddy/Caddyfile

    restart: unless-stopped
